input_file_name: "database.csv"
output_file_name: "results.csv"
sort_by_columns: ["first_name", "last_name"]
geospatial_analysis: "True"
geospatial_columns: ["lat", "lon"]
geospatial_threshold: 0.0001
fuzzy_matching: "True"
fuzzy_matching_algorithm: "semantic"  # Options: WRatio, ratio, partial_ratio, token_sort_ratio, semantic
fuzzy_threshold: 0.8
fuzzy_columns: ["address"]